default: &default
  redis_url:
    <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>
  sidekiq:
    username: <%= ENV['SIDEKIQ_USERNAME'] %>
    password: <%= ENV['SIDEKIQ_PASSWORD'] %>
  gcs:
    project: <%= ENV['GCS_PROJECT'] %>
    bucket: <%= ENV['GCS_BUCKET'] %>
    credentials:
      private_key: <%= ENV['GCS_PRIVATE_KEY']&.dump %>
      project_id: <%= ENV['GCS_PROJECT_ID'] %>
      private_key_id: <%= ENV['GCS_PRIVATE_KEY_ID'] %>
      client_email: <%= ENV['GCS_CLIENT_EMAIL'] %>
      client_id: <%= ENV['GCS_CLIENT_ID'] %>
      client_url: <%= ENV['GCS_CLIENT_URL'] %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
